name: openfold-env 
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - conda-forge::libgcc-devel_linux-aarch64
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - PyYAML==5.4.1
  - requests
  - scipy==1.7
  - tqdm==4.62.2
  - typing-extensions==4.0
  - wandb
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - nomkl
  - git
  - conda-forge::dm-tree==0.1.8
  - bioconda::hmmer
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - bioconda::mmseqs2
  - pytorch-gpu
  - pip:
      - deepspeed==0.12.4
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git@5b838a8
